[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312"]
extend-exclude = '(venv|\.venv|build|dist|\.devcontainer|\.github)'

[tool.ruff]
line-length = 88
target-version = "py310"
extend-exclude = ["venv", ".venv", "build", "dist", ".devcontainer", ".github"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
exclude = "(venv|.venv|build|dist|.devcontainer|.github)"
